### ISSUE TITLE
Reindexing/Syncing Issue W/ Blockchain

### ISSUE THREAD

**Issue by joshstewart25** [IndexChain/Index#4]
## Actual behaviour
After having the wallet open for any long period of time, the wallet will not stay synced to the blockchain, and "0" active connections to the network will occur. This also happens if the wallet has been closed for a few hours then reopened. Using -reindex helped the first time but now it's not even reindexing fully.

## Desired behaviour
Wallet will always be synced to the network when open, displaying the proper coin amount.

## Steps to reproduce
- Open wallet and keep open for an hour or so.
- Close wallet and come back after a few hours.
- Notice that there will be no active connections and the blockchain will not sync at all.

**Comment by akshaynexus** [comment]
Fixed with https://github.com/IndexChain/Index/commit/c308f8540f0c15a595ca698ac8cf489d74f43ef0
